// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5HJ53YF2tqO2fb8ZP_I1R3NratEB_jQ4',
    appId: '1:577765748244:web:ffb6a35fc4c4ad35fbc101',
    messagingSenderId: '577765748244',
    projectId: 'chat-app-test-84e56',
    authDomain: 'chat-app-test-84e56.firebaseapp.com',
    storageBucket: 'chat-app-test-84e56.firebasestorage.app',
    measurementId: 'G-QY9Q3HQB6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_l5SWfkDTHbLU5XYOATXQbcdABm1MAQ',
    appId: '1:577765748244:android:975a5c88b3ea5847fbc101',
    messagingSenderId: '577765748244',
    projectId: 'chat-app-test-84e56',
    storageBucket: 'chat-app-test-84e56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiAe9b5OCeO_9MuJi966FL_kLxgEucX8M',
    appId: '1:577765748244:ios:9de149b921e941d4fbc101',
    messagingSenderId: '577765748244',
    projectId: 'chat-app-test-84e56',
    storageBucket: 'chat-app-test-84e56.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiAe9b5OCeO_9MuJi966FL_kLxgEucX8M',
    appId: '1:577765748244:ios:9de149b921e941d4fbc101',
    messagingSenderId: '577765748244',
    projectId: 'chat-app-test-84e56',
    storageBucket: 'chat-app-test-84e56.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5HJ53YF2tqO2fb8ZP_I1R3NratEB_jQ4',
    appId: '1:577765748244:web:819b594ec530ddf8fbc101',
    messagingSenderId: '577765748244',
    projectId: 'chat-app-test-84e56',
    authDomain: 'chat-app-test-84e56.firebaseapp.com',
    storageBucket: 'chat-app-test-84e56.firebasestorage.app',
    measurementId: 'G-Q8JWTCPQXK',
  );

}